name: Continuous Deploy # action名称

on: # 在push代码的时候运行此action
  push:
    branches:
      - main
      - master

jobs:
  auto_deploy_job:
    name: build-deploy

    runs-on: ubuntu-latest # 运行环境，最新ubuntu

    strategy:
      matrix:
        node-version: [18.x] # 设置node版本，可以是多个

    steps:
      - name: Use Node.js ${{ matrix.node-version }} # 使用 node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Show version # 查看版本，方便从log信息上确认
        run: node -v && npm -v && npm config set registry https://registry.npmmirror.com

      - name: setEnv # 开启yarn和pnpm，设置源
        run: corepack enable && npm config set registry https://registry.npmmirror.com && yarn config set registry https://registry.npmmirror.com && pnpm config set registry https://registry.npmmirror.com

      - name: Checkout # check out the repository
        uses: actions/checkout@v3 # 这里使用了github官方提供的action,checkout项目到虚拟机上

      - name: Install Dependencies # 安装依赖
        run: pnpm i

      - name: Build # 构建
        run: pnpm build

      - name: Clean remote folder # 删除远程的代码
        uses: garygrossgarten/github-action-ssh@release # 使用第三方action 远程执行命令
        with:
          command: rm -rf /root/project/journey/journey-client/dist /root/project/journey/journey-client/nginx
          username: root
          host: ${{ secrets.SERVER_IP }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}

      - name: Upload build file to server # 上传dist和nginx文件
        uses: appleboy/scp-action@master # 使用第三方action 上传静态文件到服务器
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist,nginx'
          target: '/root/project/journey/journey-client'

      - name: Nginx stop # 先停止 nginx
        uses: garygrossgarten/github-action-ssh@release # 使用第三方action 远程执行命令
        with:
          command: nginx -s stop
          username: root
          host: ${{ secrets.SERVER_IP }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Nginx start # 启动 nginx
        uses: garygrossgarten/github-action-ssh@release # 使用第三方action 远程执行命令
        with:
          command: nginx -c /root/project/journey/journey-client/nginx/nginx.conf
          username: root
          host: ${{ secrets.SERVER_IP }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
